[package]
name = "divanbench"
version = "0.1.0"
edition = "2024"

[dependencies]
simdutf8 = { version = "*", path = ".." }

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "basic"
harness = false
